# theme: jekyll-theme-hacker
# title: Root@Study-With-Me:~$

remote_theme: just-the-docs/just-the-docs
title: Study With Me
description: Log ghi chép quá trình tự học lập trình và các thuật toán.

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"